---
name: release-please
on:
  push:
    branches:
    - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
    steps:
    - uses: googleapis/release-please-action@v4
      with:
        config-file: release-please-config.json
        manifest-file: .release-please-manifest.json
